# Generated by Django 4.1.4 on 2023-01-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25)),
                ('staff_image', models.ImageField(blank=True, upload_to='Staff_Image/')),
                ('dob', models.DateField()),
                ('present_address', models.CharField(max_length=100)),
                ('permenant_address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('project_done', models.CharField(max_length=100)),
                ('work_experience', models.CharField(max_length=100)),
                ('salary_expectations', models.IntegerField()),
                ('material_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('student_image', models.ImageField(blank=True, upload_to='Student_Image/')),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('hobbies', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('known_language', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('why_you_want', models.CharField(max_length=100)),
            ],
        ),
    ]
