# Generated by Django 4.1.4 on 2023-01-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_studentmodels_delete_studentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModels',
            new_name='StudentModel',
        ),
    ]
